name: red_voznje_novi_sad_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-222.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.2
  flutter_svg: ^1.0.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  http: ^0.13.5
  json_annotation: ^4.8.0
  shared_preferences: ^2.1.0
  collection: ^1.15.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.2
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.12
  json_serializable: ^6.6.0

flutter:

  uses-material-design: true
  assets:
    - lib/assets/
